# Generated by Django 5.2.5 on 2026-03-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information_System', '0003_migrate_admin_users'),
    ]

    operations = [
    ]
