# Generated by Django 5.2.5 on 2026-03-19 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_System', '0004_migrate_admin_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
        migrations.AlterModelTable(
            name='adminauthorization',
            table='admin_authorizations',
        ),
        migrations.AlterModelTable(
            name='boardexamarea',
            table='board_exam_areas',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='coursemapping',
            table='course_mappings',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='integrationcourse',
            table='integration_courses',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrator'), ('faculty', 'Faculty'), ('program_chair', 'Program Chair')], default='admin', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Information_System.admin')),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.AlterField(
            model_name='adminauthorization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to='Information_System.admin'),
        ),
        migrations.AlterField(
            model_name='adminauthorization',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to='Information_System.admin'),
        ),
        migrations.CreateModel(
            name='AdminLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_successful', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='Information_System.admin')),
            ],
            options={
                'verbose_name_plural': 'Admin Login Histories',
                'db_table': 'admin_login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
