# Generated by Django 5.2.5 on 2026-03-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information_System', '0005_remove_passwordreset_user_remove_user_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
